lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BlogWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/blogs", BlogsController, :index

    get "/blogs/:id", BlogsController, :single

    get "/write", BlogsController, :write

    get "/edit/:id", BlogsController, :edit

    get "/delete/:id", BlogsController, :delete_post

    get "delete_comment/:id", BlogsController, :delete_comment

    post "/update", BlogsController, :update

    post "/save", BlogsController, :save

    post "/savecomment", BlogsController, :savecomment
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/blog/app.ex
defmodule Blog.App do
  alias Blog.Schemas.{User, Post, Comment}
  alias Blog.Repo
  alias Ecto.Changeset
  import Ecto.Query

  def list_posts() do
    IO.puts("list_posts called")

    query =
      from p in Post,
        order_by: [desc: p.id],
        preload: :user

    Repo.all(query)
  end

  def single(id) do
    Repo.get(Post, id) |> Repo.preload([:comments])
  end

  def user(id) do
    Repo.get(User, id)
  end

  def save(id, post) do
    user = Repo.get(User, id)
    text = post["post_text"]
    title = post["post_title"]
    Repo.insert(%Post{post_title: title, post_text: text, user: user})
  end

  def savecomment(comment, post, user) do
    Repo.insert(%Comment{comment_text: comment, post: post, user: user})
  end

  def delete_post(id) do
    Post
    |> Repo.get(id)
    |> Repo.delete()
  end

  def delete_comment(id) do
    Comment |> Repo.get(id) |> Repo.delete()
  end

  def update_post(id, title, text) do
    post = Repo.get!(Post, id)
    post = Ecto.Changeset.change(post, post_title: title, post_text: text)
    Repo.update(post)
  end
end

lib/blog/application.ex
defmodule Blog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Blog.Repo,
      # Start the Telemetry supervisor
      BlogWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Blog.PubSub},
      # Start the Endpoint (http/https)
      BlogWeb.Endpoint
      # Start a worker by calling: Blog.Worker.start_link(arg)
      # {Blog.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    BlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/blog/mailer.ex
defmodule Blog.Mailer do
  use Swoosh.Mailer, otp_app: :blog
end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo,
    otp_app: :blog,
    adapter: Ecto.Adapters.Postgres
end

lib/blog/schemas/comment.ex
defmodule Blog.Schemas.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :comment_text, :string

    belongs_to :post, Blog.Schemas.Post
    belongs_to :user, Blog.Schemas.User

    timestamps()
  end

  def changeset(comment, params \\ %{}) do
    comment
    |> cast(params, [:comment_text])
    |> validate_required([:comment_text])
  end
end

lib/blog/schemas/post.ex
defmodule Blog.Schemas.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :post_title, :string
    field :post_text, :string

    has_many :comments, Blog.Schemas.Comment
    belongs_to :user, Blog.Schemas.User

    timestamps()
  end

  def changeset(post, params \\ %{}) do
    post
    |> cast(params, [:post_title, :post_text])
    |> validate_required([:post_text])
  end
end

lib/blog/schemas/user.ex
defmodule Blog.Schemas.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :username, :string
    has_many :posts, Blog.Schemas.Post
    has_many :comments, Blog.Schemas.Comment

    timestamps()
  end

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:username])
    |> validate_required([:username])
  end
end

lib/blog_web/controllers/blogs_controller.ex
defmodule BlogWeb.BlogsController do
  use BlogWeb, :controller

  alias Blog.App
  alias Blog.Schemas.Post
  alias Blog.Schemas.Comment

  def index(conn, _params) do
    posts = App.list_posts()
    changeset = Post.changeset(%Post{}, %{})
    render(conn, "index.html", posts: posts, changeset: changeset)
  end

  def single(conn, %{"id" => id}) do
    post = App.single(id)
    changeset = Comment.changeset(%Comment{}, %{})
    render(conn, "single.html", post: post, changeset: changeset, id: id)
  end

  def write(conn, _params) do
    changeset = Post.changeset(%Post{}, %{})
    render(conn, "create.html", changeset: changeset)
  end

  def save(conn, %{"post" => post}) do
    # IO.puts(conn)
    # IO.puts(params)

    # render(conn, "check.html", check: check)
    # IO.inspect(post)
    App.save(1, post)
    redirect(conn, to: "/blogs")
  end

  def savecomment(conn, params) do
    data = params["comment"]

    comment = data["comment_text"]
    id = data["id"]

    IO.puts(id)

    IO.puts(comment)

    post = App.single(id)

    user = App.user(1)

    saved = App.savecomment(comment, post, user)

    changeset = Comment.changeset(%Comment{}, %{})

    redirect(conn, to: "/blogs/#{id}")
    # render(conn, "single.html", post: post, changeset: changeset, id: id)
  end

  def edit(conn, %{"id" => id}) do
    IO.inspect(id)
    post = App.single(id)
    IO.inspect(post)
    changeset = Post.changeset(%Post{}, %{})
    render(conn, "update.html", id: id, post: post, changeset: changeset)
  end

  def update(conn, %{"post" => %{"id" => id, "text" => text, "title" => title}}) do
    App.update_post(id, title, text)
    redirect(conn, to: "/blogs")
  end

  def delete_post(conn, %{"id" => id}) do
    App.delete_post(id)
    redirect(conn, to: "/blogs")
  end

  def delete_comment(conn, %{"id" => id}) do
    post = App.delete_comment(id)
    {:ok, post} = post
    post_id = post.post_id
    redirect(conn, to: "/blogs/#{post_id}")
    # render(conn, "check.html", id: id)
  end
end

lib/blog_web/controllers/page_controller.ex
defmodule BlogWeb.PageController do
  use BlogWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/blog_web/views/blogs_view.ex
defmodule BlogWeb.BlogsView do
  use BlogWeb, :view

end

lib/blog_web/views/error_view.ex
defmodule BlogWeb.ErrorView do
  use BlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/blog_web/views/page_view.ex
defmodule BlogWeb.PageView do
  use BlogWeb, :view
end

lib/blog_web/templates/blogs/check.html.heex
<h1><%= @id %></h1>

lib/blog_web/templates/blogs/create.html.heex
<%= form_for @changeset, Routes.blogs_path(@conn, :save), fn f -> %>

  <label>
    Post Title: <%= text_input f, :post_title %>
  </label>

  <label>
    Post Text: <%= text_input f, :post_text %>
  </label>

  <%= submit "Submit" %>
<% end %>

lib/blog_web/templates/blogs/index.html.heex
<div>
    
    <%= link("Write", to: "/write") %>

</div>
<br>
<h1>Blogs</h1>



<%= for post <- @posts do%>
<div>
    <h3><%= link("#{post.post_title}", to: "/blogs/#{post.id}", method: :get)  %></h3>
    <span> created by <%= post.user.username %></span>
    <hr>
</div>

<% end %>

lib/blog_web/templates/blogs/single.html.heex
<h1 style="text-decoration: underline"><%= @post.post_title%></h1>

<div><%= link("Edit", to: "/edit/#{@id}") %>
    <%= link("Delete", to: "/delete/#{@id}") %>
</div>

<h4><%= @post.post_text%></h4>

<%= form_for @changeset, Routes.blogs_path(@conn, :savecomment), fn f -> %>

<label> Add Comment: <%= text_input f, :comment_text %> </label>

<%= hidden_input(f, :id ,value: @id) %> <%= submit "Submit" %> <% end %>

<h4 style="text-decoration: underline">Comments:</h4>
<%= for comment <- @post.comments do%>

<div>
    <p><%= comment.comment_text %></p>
    <%= link("Delete", to: "/delete_comment/#{comment.id}") %>
</div>
<hr />
<% end %>

lib/blog_web/templates/blogs/update.html.heex
<%= form_for @changeset, Routes.blogs_path(@conn, :update), fn f -> %>

<h1>Post Title</h1>
<label> <%= text_input f, :title, value: @post.post_title%> </label>
<h1>Post Text</h1>
<label> <%= textarea f, :text, value: @post.post_text%> </label>
<%= submit "Submit" %> <%= hidden_input(f, :id ,value: @id) %> <% end %>

lib/blog_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/blog_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/blog_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Blog", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://localhost:4000/blogs" class="phx-logo">
         <h1>Blog Website</h1>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/blog_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>